<?php

namespace AppBundle\Repository;

/**
 * UnseiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UnseiRepository extends \Doctrine\ORM\EntityRepository
{
}
